/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "Math.h"
#include "STD_Type.h"
#include "RCC_Interface.h"

#include "../DIO/GPIO_Interface.h"
u8 x=10;
void led ()
{
	GPIO_V_Set_Pin_value(PinA_0_High);
}
int main(void)
{
	RCC_V_InitCLK();
	RCC_V_EnablePer(0, 0);
	RCC_V_SetCallBack(led);

    /* Loop forever */

	for(;;);
}
